#应用说明
application:
  name: java Spyide
  chineseName: java爬虫
  author: advance
  version: V1.0
  realName: 周韩

#项目部署配置
server:
  port: 80
  servlet:
    context-path: /api/v1.0/reader/
#  ssl:
#    key-store: classpath:server.keystore
#    key-alias: tomcat
#    enabled: true
#    key-store-password: 123456
#    key-store-type: JKS
#数据源配置
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://134.175.3.16:3306/reptile?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&amp
#    url: jdbc:mysql://localhost:3306/reptile?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&amp
    username: root
    password: Zhouhan19970517$
    hikari:
      max-lifetime: 1200000
    tomcat:
      max-wait: 10000
      max-idle: 10
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

  data:
    mongodb:
      database: reptile
      #地址
      host: 134.175.3.16
      #端口号
      port: 27017
  redis:
    port: 6379
    host: 134.175.3.16
    timeout: 10
    jedis:
      pool:
        max-idle: 500
        max-active: 1000
        max-wait: 500
        min-idle: 0
    password: 123456
#    rabbitMq配置
  rabbitmq:
      host: 134.175.3.16
      username: root
      password: 123456
      port: 5672
      virtual-host: /
      #消息发送和接收确认
      publisher-confirms: true
      publisher-returns: true
      listener:
        direct:
          acknowledge-mode: manual
        simple:
          acknowledge-mode: manual
#日志配置
logging:
  config: classpath:logback.xml

#mybatis-plus配置
mybatis-plus:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.advance.reptile.*.entity

